Fix dependencies
electrumpayments/giftcard-service-interface pull request #34
Opened 2022-01-31 09:12 UTC by PatrickColborne

2022-04-07 20:57 UTC, mpendulocele-electrum requested changes

2022-04-07 20:57 UTC, mpendulocele-electrum commented on pom.xml
> +    <service-interface-base-version>3.37.2-SNAPSHOT</service-interface-base-version>
You can release v3.38.1 and update this dependency or use v3.38.0

2022-04-07 20:57 UTC, mpendulocele-electrum commented on README.md
> +    <version>3.37.2</version>
Don't forget to match this version with the one you will use in the pom file

2022-04-07 20:57 UTC, mpendulocele-electrum commented on pom.xml
> +    <major-version>4</major-version>
Are we marking this as a breaking change because we are adding a new `provided` dependency?

2022-04-08 09:23 UTC, PatrickColborne commented on pom.xml
> +    <major-version>4</major-version>
It's a breaking change because I removed a bunch of dependencies that were being compiled in here. Anything that required those dependencies will have to get them from elsewhere now and that could break something.

2022-04-08 09:29 UTC, PatrickColborne commented on README.md
> +    <version>3.37.2</version>
Updated it thanks

2022-04-13 16:15 UTC, merged